apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: clientcallback
spec:
  type: bindings.azure.signalr
  version: v1
  metadata:
  - name: connectionString
    value: Endpoint=http://signalr:8888;Port=8888;AccessKey=ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ABCDEFGH;Version=1.0;
  - name: hub 
    value: spinozahub