name: Containers App Integration Tests

on:
  workflow_dispatch:
  workflow_call:
    
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: |
          6.0.x
    - name: find containers app urls
      run: |
        export accountManagerFQDN=`az containerapp show --resource-group "bmsd-cont-app-rg" --name accountmanager --query properties.configuration.ingress.fqdn | tr -d '"'`
        export notificationManagerFQDN=`az containerapp show --resource-group "bmsd-cont-app-rg" --name accountmanager --query properties.configuration.ingress.fqdn | tr -d '"'`
    - name: Test
      env:
        BMSD_SIGNALR_URL: ${{ env.notificationManagerFQDN }}
        ACCOUNT_MANAGER_URL: ${{ env.notificationManagerFQDN }}
      run: dotnet test --verbosity normal --configuration Release Tests/BMSD.Tests.IntegrationTests/BMSD.Tests.IntegrationTests.csproj
    
