name: Containers App Integration Tests

on:
  workflow_dispatch:
  workflow_call:
    
jobs:
  build:
    runs-on: ubuntu-latest
    environment: test
    defaults:
      run:
        shell: bash
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Find containers app urls 
      run: |
          az config set extension.use_dynamic_install=yes_without_prompt'
          export AccountManagerFQDN=`az containerapp show --resource-group "bmsd-cont-app-rg" --name accountmanager --query properties.configuration.ingress.fqdn | tr -d '"'`
          export NotificationManagerFQDN=`az containerapp show --resource-group "bmsd-cont-app-rg" --name notifiactionmanager --query properties.configuration.ingress.fqdn | tr -d '"'`
          echo "Account Manager Url: $AccountManagerFQDN"
          echo "Notification Manager Url: $NotificationManagerFQDN"
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: |
          6.0.x
    - name: Test
      env:
        BMSD_SIGNALR_URL: ${{ env.NotificationManagerFQDN }}
        ACCOUNT_MANAGER_URL: ${{ env.AccountManagerFQDN }}
      run: dotnet test --verbosity normal --configuration Release Tests/BMSD.Tests.IntegrationTests/BMSD.Tests.IntegrationTests.csproj
    
