name: Deploy Azure Container Apps Environment

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: test
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az account show
          az group create --name bmsd-cont-app-rg --location eastus2
          az deployment group create --resource-group bmsd-cont-app-rg --template-file infra/main.bicep \
            --parameters branchName='master' \
            containerRegistry='bmsdcr.azurecr.io' \
            containerRegistryUsername="${{secrets.ACR_USERNAME}}" \
            containerRegistryPassword="${{secrets.ACR_PASSWORD}}" \
            cosmosDBConnectionString="${{secrets.COSMOSDB_CONNECTION_STRING}}" \
            cosmosDBKey="${{secrets.COSMOSDB_KEY}}" \
            cosmosDBDatabaseName=BMSDB \
            
          
