name: Deploy Azure Container Apps Environment

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: test
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az account show
          az group create --name bmsd-containers-app-rg --location westeurope 
          #eastus2
          #use this command and paste the output to the AZURE_CREDENTIALS secret
          #az ad sp create-for-rbac --name "bmsd" --role contributor --scopes /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/bmsd-cont-app-rg --sdk-auth
          az deployment group create --resource-group bmsd-containers-app-rg --template-file infra/main.bicep \
            --parameters branchName='master' \
            containerRegistry='bmsdcr.azurecr.io' \
            containerRegistryUsername="${{secrets.ACR_USERNAME}}" \
            containerRegistryPassword="${{secrets.ACR_PASSWORD}}" \
            cosmosDBConnectionString="${{secrets.BMSD_COSMOSDB_CONNECTION_STRING}}" \
            cosmosDbUrl=${{secrets.COSMOSDB_URL}} \
            cosmosDBKey="${{secrets.COSMOSDB_KEY}}" \
            cosmosDBDatabaseName=BMSDB \
            
          
