name: Full CI CD Workflow

on:
  workflow_dispatch:
  
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: test
    steps:
    - name: Run CI Workflow
      uses: ./.github/workflows/IntegrationTest.yml
    - name: Deploy Docker Images
      uses: ./.github/workflows/PushDockerImages.yml
    - name: Deploy Azure Containers App
      uses: ./.github/workflows/DeployContainersApp.yml
    - name: Wait to let deployment finelized 
      run: sleep 120s
      shell: bash
    - name: Test the deployment services
      uses: ./.github/workflows/ContainersAppIntegrationTest.yml
            
