name: Build & publish docker images
on:
  workflow_dispatch:
  workflow_call:
  release:
    types: [published]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    environment: test
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./Managers/BMSD.Managers.Account/Dockerfile
            image: bmsd.managers.account
            application_name: accountmanager
          - dockerfile: ./Managers/BMSD.Managers.Notification/Dockerfile
            image: bmsd.managers.notification
            application_name: notificationmanager
          - dockerfile: ./Accessors/BMSD.Accessors.CheckingAccount/Dockerfile
            image: bmsd.accessors.checkingaccount
            application_name: checkingaccountaccessor
          - dockerfile: ./Accessors/BMSD.Accessors.UserInfo/Dockerfile
            image: bmsd.accessors.userinfo
            application_name: userinfoaccessor
          - dockerfile: ./Engines/BMSD.Engines.LiabilityValidator/Dockerfile
            image: bmsd.engines.liabilityvalidator
            application_name: liabilityvalidatorengine
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: azure/docker-login@v1
        with:
          login-server: bmsdcr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: bmsdcr.azurecr.io/${{ matrix.image }}
      - name: Build and push Docker images
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Update containers app revision
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp update --name ${{ matrix.application_name }} --resource-group bmsd-cont-app-rg --image bmsdcr.azurecr.io/${{ matrix.image }}:${GITHUB_REF#refs/heads/}