 name: Push Docker Images to ACR 
 on:
  workflow_dispatch:
   workflow_call:
   release:
    types: [published]

 jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    environment: test
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: 
            image: ${DOCKER_REGISTRY-}gallerubackendmanagerusers
            application_name: managerusers
          - dockerfile: ./backend/GallerUBackEnd/Accessors/GallerU.Backend.Accessor.Users/Dockerfile
            image: ${DOCKER_REGISTRY-}gallerubackendaccessorusers
            application_name: gallerubackendaccessorevent
          - dockerfile: ./backend/GallerUBackEnd/Accessors/GallerU.Backend.Accessor.Event/Dockerfile
            image: ${DOCKER_REGISTRY-}gallerubackendaccessorevent
            application_name: gallerubackendmanagerevent
          - dockerfile: ./backend/GallerUBackEnd/Managers/GallerU.Backend.Manager.Event/Dockerfile
            image: ${DOCKER_REGISTRY-}gallerubackendaccessoruserevent
            application_name: accessoruserevent
          - dockerfile: Accessors/GallerU.Backend.Accessor.UserEvent/Dockerfile
            image:  ${DOCKER_REGISTRY-}gallerubackendaccessoeventtemplatecatalog
            application_name: accessoeventtemplatecatalog
          - dockerfile: ./backend/GallerUBackEnd/Accessors/GallerU.Backend.Accessor.EventTemplateCatalog/Dockerfile
            image: ${DOCKER_REGISTRY-}gallerubackendmanagersnotification
            application_name: accessoruserevent
          - dockerfile: ./backend/GallerUBackEnd/Managers/GallerU.Backend.Managers.Notification/Dockerfile

           
    permissions:
      contents: read
      packages: write

    steps:
    # Install Docker
    - run: |
        sudo apt-get update
        sudo apt-get install -y docker.io
        echo "Docker installed successfully."
    # Login to Azure Container Registry
    - run: |
        az acr login --name [galleruacr]
        echo "Logged in to Azure Container Registry."
           # Build and push all Docker images
    - run: |
        docker images | awk '/^[^<none>]/ {print $1":"$2}' | \
        while read -r line; do
          imageName=${line%:*}
          imageTag=${line#*:}
          docker tag $imageName [acr_name].azurecr.io/$imageName:$imageTag
          docker push [acr_name].azurecr.io/$imageName:$imageTag
        done
        echo "All images pushed to Azure Container Registry."
